targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern: ".*Service$|.*Repository$|.*UseCase$|.*DataSource$"
          file_name_pattern: "_service$|_repository$|_usecase$|_datasource$"
      mockito|mockBuilder:
        generate_for:
          - test/**.dart 